<?php
// =====================
// Fcz-v2 bootstrap file
// =====================

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// CREATE DEPENDENCY INJECTION CONTAINER FROM CONFIG.NEON FILE

// Global config
$configurator->addConfig(__DIR__ . '/config/config.neon');

// Machine config
$localConfig = __DIR__ . '/config/config.local.neon';
$errorMsg = "
	<h1>Configuration error</h1>
	<p>Please create local configuration file <span style='font-family:monospace;'>$localConfig</span>
	with configuration specific to your machine (database access for instance).
	</p>
	<p>Example:
	<pre>
	parameters:

	nette:
	    database:
	        default:
	            dsn: 'mysql:host=localhost;dbname=fcz-v2'
	            user: fcz
	            password: fcz
	            reflection: discovered

	services:

	factories:</pre></p>";
if (!is_file(__DIR__ . '/config/config.local.neon'))
{
	die($errorMsg);
}
$configurator->addConfig($localConfig, $configurator::NONE); // none section

// Base directory param
$configurator->addParameters(array(
	'baseDirectory' => realpath(__DIR__ . "/..")
));

// Build the container
$container = $configurator->createContainer();

return $container;
