CREATE TABLE `Users` (
  `Id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `Username` varchar(50) COLLATE utf8_czech_ci NOT NULL COMMENT 'Login only',
  `Nickname` varchar(100) COLLATE utf8_czech_ci NOT NULL COMMENT 'Display name',
  `Password` tinytext COLLATE utf8_czech_ci NOT NULL,
  `Salt` tinytext COLLATE utf8_czech_ci NOT NULL,
  `OtherNicknames` tinytext COLLATE utf8_czech_ci COMMENT 'Furry',
  `Species` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Furry',
  `FurrySex` enum('Male','Female','Herm','Sexless') COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Furry',
  `ShortDescriptionForMembers` text COLLATE utf8_czech_ci COMMENT 'Furry',
  `ShortDescriptionForGuests` text COLLATE utf8_czech_ci COMMENT 'Furry',
  `ProfileForMembers` int(11) unsigned DEFAULT NULL COMMENT 'FK - CMS page id',
  `ProfileForGuests` int(11) unsigned DEFAULT NULL COMMENT 'FK - CMS page id',
  `ImageGalleryPresentation` int(11) unsigned DEFAULT NULL COMMENT 'FK - CMS page id',
  `WritingsPresentation` int(11) unsigned DEFAULT NULL COMMENT 'FK - CMS page id',
  `AvatarFilename` varchar(50) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Furry',
  `FullName` varchar(50) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `Address` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `RealSex` enum('Male','Female') COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `DateOfBirth` date NOT NULL COMMENT 'Real',
  `FavouriteWebsites` text COLLATE utf8_czech_ci COMMENT 'Real',
  `ProfilePhotoFilename` varchar(50) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `Hobbies` text COLLATE utf8_czech_ci COMMENT 'Real',
  `GoogleMapsLink` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `DistanceFromPrague` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `WillingnessToTravel` enum('Small','Medium','Big') COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `Email` varchar(100) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Real',
  `LastLogin` datetime DEFAULT NULL COMMENT 'Cache',
  `LastVisitedPage` varchar(25) COLLATE utf8_czech_ci DEFAULT NULL COMMENT 'Cache',
  `LastActivityTime` datetime DEFAULT NULL COMMENT 'Cache',
  `SendIntercomToMail` tinyint(1) unsigned DEFAULT '0' COMMENT 'Config',
  `PostsOrdering` enum('NewestOnTop','OldestOnTop') COLLATE utf8_czech_ci NOT NULL DEFAULT 'NewestOnTop' COMMENT 'Config',
  `PostsPerPage` int(10) unsigned NOT NULL DEFAULT '25' COMMENT 'Config',
  `IsAdmin` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Admin',
  `IsApproved` tinyint(1) unsigned DEFAULT '0' COMMENT 'Admin',
  `IsBanned` tinyint(1) unsigned DEFAULT '0' COMMENT 'Admin',
  `IsFrozen` tinyint(1) unsigned DEFAULT '0' COMMENT 'Admin',
  `Deleted` tinyint(1) unsigned DEFAULT '0' COMMENT 'Admin',
  PRIMARY KEY (`Id`),
  KEY `ImageGalleryPresentation` (`ImageGalleryPresentation`),
  KEY `ProfileForGuests` (`ProfileForGuests`),
  KEY `WritingsPresentation` (`WritingsPresentation`),
  KEY `ProfileForMembers` (`ProfileForMembers`),
  CONSTRAINT `Users_ibfk_17` FOREIGN KEY (`ImageGalleryPresentation`) REFERENCES `CmsPages` (`Id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `Users_ibfk_14` FOREIGN KEY (`ProfileForGuests`) REFERENCES `CmsPages` (`Id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `Users_ibfk_15` FOREIGN KEY (`WritingsPresentation`) REFERENCES `CmsPages` (`Id`) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT `Users_ibfk_16` FOREIGN KEY (`ProfileForMembers`) REFERENCES `CmsPages` (`Id`) ON DELETE SET NULL ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_czech_ci