ALTER TABLE `Access`
DROP FOREIGN KEY `Access_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE RESTRICT;

ALTER TABLE `Access`
DROP FOREIGN KEY `Access_ibfk_2`,
ADD FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE RESTRICT;

ALTER TABLE `Access`
DROP FOREIGN KEY `Access_ibfk_3`,
ADD FOREIGN KEY (`PermissionId`) REFERENCES `Permissions` (`Id`) ON DELETE NO ACTION ON UPDATE RESTRICT;