ALTER TABLE `Contacts`
DROP FOREIGN KEY `Contacts_ibfk_1`,
ADD FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Contacts`
DROP FOREIGN KEY `Contacts_ibfk_2`,
ADD FOREIGN KEY (`TypeId`) REFERENCES `ContactTypes` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;