ALTER TABLE `Events`
DROP FOREIGN KEY `Events_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Events`
DROP FOREIGN KEY `Events_ibfk_2`,
ADD FOREIGN KEY (`Header`) REFERENCES `CmsPages` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;