ALTER TABLE `Ignorelist`
DROP FOREIGN KEY `Ignorelist_ibfk_1`,
ADD FOREIGN KEY (`IgnoringUserId`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Ignorelist`
DROP FOREIGN KEY `Ignorelist_ibfk_2`,
ADD FOREIGN KEY (`IgnoredUserId`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;