ALTER TABLE `Images`
DROP FOREIGN KEY `Images_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Images`
DROP FOREIGN KEY `Images_ibfk_2`,
ADD FOREIGN KEY (`UploadedFileId`) REFERENCES `UploadedFiles` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;