ALTER TABLE `Ownership`
DROP FOREIGN KEY `Ownership_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE RESTRICT;

ALTER TABLE `Ownership`
DROP FOREIGN KEY `Ownership_ibfk_2`,
ADD FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE RESTRICT;