ALTER TABLE `PollVotes`
DROP FOREIGN KEY `PollVotes_ibfk_1`,
ADD FOREIGN KEY (`PollId`) REFERENCES `Polls` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `PollVotes`
DROP FOREIGN KEY `PollVotes_ibfk_2`,
ADD FOREIGN KEY (`AnswerId`) REFERENCES `PollAnswers` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `PollVotes`
DROP FOREIGN KEY `PollVotes_ibfk_3`,
ADD FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;