ALTER TABLE `Posts`
DROP FOREIGN KEY `Posts_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Posts`
DROP FOREIGN KEY `Posts_ibfk_2`,
ADD FOREIGN KEY (`Author`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;