ALTER TABLE `Ratings`
DROP FOREIGN KEY `Ratings_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Ratings`
DROP FOREIGN KEY `Ratings_ibfk_2`,
ADD FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;