ALTER TABLE `RatingsPost`
DROP FOREIGN KEY `ratingspost_ibfk_1`,
ADD FOREIGN KEY (`PostId`) REFERENCES `Posts` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `RatingsPost`
DROP FOREIGN KEY `ratingspost_ibfk_2`,
ADD FOREIGN KEY (`UserId`) REFERENCES `Users` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `RatingsPost`
DROP FOREIGN KEY `ratingspost_ibfk_3`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE RESTRICT ON UPDATE RESTRICT;