ALTER TABLE `Topics`
DROP FOREIGN KEY `Topics_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Topics`
DROP FOREIGN KEY `Topics_ibfk_2`,
ADD FOREIGN KEY (`CategoryId`) REFERENCES `TopicCategories` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Topics`
DROP FOREIGN KEY `Topics_ibfk_3`,
ADD FOREIGN KEY (`Header`) REFERENCES `CmsPages` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Topics`
DROP FOREIGN KEY `Topics_ibfk_4`,
ADD FOREIGN KEY (`HeaderForDisallowedUsers`) REFERENCES `CmsPages` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;