ALTER TABLE `Writings`
DROP FOREIGN KEY `Writings_ibfk_1`,
ADD FOREIGN KEY (`ContentId`) REFERENCES `Content` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `Writings`
DROP FOREIGN KEY `Writings_ibfk_2`,
ADD FOREIGN KEY (`CategoryId`) REFERENCES `WritingCategories` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION;